# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    url_validator:
        class: AppBundle\Services\FilterValidatorService
    filter_manager:
        class: AppBundle\Services\FilterManager
        arguments: ["@doctrine.orm.default_entity_manager", "@translator", "@url_validator", '@app.sqs_queue']

    mail:
        class: AppBundle\Services\Mail
        arguments: ["@mailer", "@templating", "@translator"]

    user_service:
        class: AppBundle\Services\UserService
        arguments: ["@fos_user.user_manager", "@fos_user.util.token_generator"]

    app.exception_listiner:
        class: AppBundle\EventListener\ExceptionListener
        arguments: ['@monolog.logger.exceptions', '@translator.default']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 1 }