<?php

namespace AppBundle\Services\Queue;

use Aws\Sqs\SqsClient;
use Exception;
use function json_encode;

class Queue
{
    /**
     * @var SqsClient
     */
    private $client;

    /**
     * @var string
     */
    private $url;

    public function __construct(SqsClient $client, string $url)
    {
        $this->client = $client;
        $this->url = $url;
    }

    /**
     * @param Message $message
     */
    public function send(array $data)
    {
        try {
            $this->client->sendMessage(array(
                'QueueUrl' => $this->url,
                'MessageBody' => json_encode($data),
            ));

            return true;
        } catch (\Exception $e) {
            #log it
        }

        return false;
    }

    /**
     * @return Message|bool
     */
    public function receive()
    {
        $msgBig = '{
  "data": {
    "57": {
      "items": [
        {
          "title": "Parduodami namų valdos sklypai E.pliaterytės",
          "url": "https://www.skelbiu.lt/skelbimai/parduodami-namu-valdos-sklypai-e-pliaterytes-23-ir-25-ir-29801643.html",
          "price": "8 777 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 57,
          "item": "ads29801643",
          "details": "Kaunas, Vaišvydava, Kračkiemio g. 7.00 a |  Namų valda",
          "filter_name": "sklypas",
          "id": 2446,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Naujai formuojamame kvartele, Vaišvydavoje,",
          "url": "https://www.skelbiu.lt/skelbimai/naujai-formuojamame-kvartele-vaisvydavoje-parduodami-29759981.html",
          "price": "7 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 57,
          "item": "ads29759981",
          "details": "Kaunas, Vaišvydava, Vienkiemių g. 7.00 a |  Namų valda",
          "filter_name": "sklypas",
          "id": 2447,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Parduodamas Namų Valdos Sklypas Prie Garšvės",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-namu-valdos-sklypas-prie-garsves-upelio-29724689.html",
          "price": "8 525 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 57,
          "item": "ads29724689",
          "details": "Kaunas, Vaišvydava, Šienpjovių g. 7.75 a |  Namų valda",
          "filter_name": "sklypas",
          "id": 2448,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Parduodamas Kauno mieste Vaišvydavoje Garšvės",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-kauno-mieste-vaisvydavoje-garsves-g-namu-valdos-29709483.html",
          "price": "8 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 57,
          "item": "ads29709483",
          "details": "Kaunas, Vaišvydava, Garšvės g. 7.43 a |  Namų valda",
          "filter_name": "sklypas",
          "id": 2450,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Kauno m. sav., Kauno m., Vaišvydava",
          "url": "https://www.skelbiu.lt/skelbimai/kauno-m-sav-kauno-m-vaisvydava-29674657.html",
          "price": "9 900 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 57,
          "item": "ads29674657",
          "details": "Kaunas, Vaišvydava, Aštrago g. 6.00 a |  Namų valda",
          "filter_name": "sklypas",
          "id": 2451,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Parduodamas 9.70a sklypas, vienbučių ir",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-9-70a-sklypas-vienbuciu-ir-dvibuciu-gyvenamuju-29601891.html",
          "price": "9 500 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 57,
          "item": "ads29601891",
          "details": "Kaunas, Vaišvydava, Pasagos g. 9.70 a |  Namų valda",
          "filter_name": "sklypas",
          "id": 2453,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Parduodami namų valdos sklypai naujai",
          "url": "https://www.skelbiu.lt/skelbimai/parduodami-namu-valdos-sklypai-naujai-formuojamoje-29585409.html",
          "price": "8 970 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 57,
          "item": "ads29585409",
          "details": "Kaunas, Aleksotas 8.97 a |  Namų valda",
          "filter_name": "sklypas",
          "id": 2456,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Sklypai Vaišvydavoje",
          "url": "https://www.skelbiu.lt/skelbimai/sklypai-vaisvydavoje-noredami-susisiekti-su-brokeriu-29388739.html",
          "price": "9 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 57,
          "item": "ads29388739",
          "details": "Kaunas, Vaišvydava, Vienkiemių g. 8.00 a |  Namų valda",
          "filter_name": "sklypas",
          "id": 2457,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Parduodami Žemės Sklypai, Kauno Mieste,",
          "url": "https://www.skelbiu.lt/skelbimai/parduodami-zemes-sklypai-kauno-mieste-vaisvydavoje-29359005.html",
          "price": "6 800 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 57,
          "item": "ads29359005",
          "details": "Kaunas, Vaišvydava, Vienkiemių g. 6.14 a |  Namų valda",
          "filter_name": "sklypas",
          "id": 2459,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Pirksime Soda",
          "url": "https://www.skelbiu.lt/skelbimai/pirksime-soda-29338859.html",
          "price": "Ieško",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 57,
          "item": "ads29338859",
          "details": "Kaunas, Panemunė, Kaniūkų 1-oji g. 6.00 a |  Namų valda",
          "filter_name": "sklypas",
          "id": 2461,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Perku Namu Valdos Sklypa Fredoje Biruteje",
          "url": "https://www.skelbiu.lt/skelbimai/perku-namu-valdos-sklypa-fredoje-biruteje-29288435.html",
          "price": "Ieško",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 57,
          "item": "ads29288435",
          "details": "Kaunas, Aleksotas, O. Milašiaus g. 6.00 a |  Namų valda",
          "filter_name": "sklypas",
          "id": 2462,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Parduodamas Kauno mieste 7.aru sklipas su projaktu",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-kauno-mieste-7-aru-sklipas-su-projaktu-29303647.html",
          "price": "38 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 57,
          "item": "ads29303647",
          "details": "Kaunas, Dainava, Žiogų takas 7.00 a |  Namų valda",
          "filter_name": "sklypas",
          "id": 2464,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Parduodami namų valdos sklypai Kaune,",
          "url": "https://www.skelbiu.lt/skelbimai/parduodami-namu-valdos-sklypai-kaune-juodelynes-g-naujai-29108799.html",
          "price": "9 900 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 57,
          "item": "ads29108799",
          "details": "Kaunas, Aleksotas, Juodelynės g. 9.00 a |  Namų valda",
          "filter_name": "sklypas",
          "id": 2465,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Parduodami 8-9a namų valdos žemės sklypai",
          "url": "https://www.skelbiu.lt/skelbimai/parduodami-8-9-a-namu-valdos-zemes-sklypai-panemuneje-kaune-29103967.html",
          "price": "9 317 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 57,
          "item": "ads29103967",
          "details": "Kaunas, Panemunė, K. Paltaroko g. 8.47 a |  Namų valda",
          "filter_name": "sklypas",
          "id": 2467,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Sklypų kvartalas Aleksote, P. Skardžiaus g. \r",
          "url": "https://www.skelbiu.lt/skelbimai/sklypu-kvartalas-aleksote-p-skardziaus-g-sklypai-ribojasi-su-29047507.html",
          "price": "7 800 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 57,
          "item": "ads29047507",
          "details": "Kaunas, Aleksotas, P. Skardžiaus g. 6.00 a |  Namų valda |  Daugiaaukščiams statiniams",
          "filter_name": "sklypas",
          "id": 2468,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Parduodami 4 sklypai po 8-9 arus Kaune,",
          "url": "https://www.skelbiu.lt/skelbimai/parduodami-4-sklypai-po-8-9-arus-kaune-vaisvydavoje-ribojasi-28995781.html",
          "price": "9 999 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 57,
          "item": "ads28995781",
          "details": "Kaunas, Vaišvydava, Vienkiemių g. 8.50 a |  Namų valda",
          "filter_name": "sklypas",
          "id": 2471,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Namų valdos žemės sklypas Kauno m",
          "url": "https://www.skelbiu.lt/skelbimai/namu-valdos-zemes-sklypas-kauno-m-vaisvydavoje-gyvenamuju-29232321.html",
          "price": "1 050 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 57,
          "item": "ads29232321",
          "details": "Kaunas, Vaišvydava, Vienkiemių g. 8.00 a |  Namų valda",
          "filter_name": "sklypas",
          "id": 2472,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Parduodamas 8 a Rokeliose\r",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-8-a-rokeliose-investicija-i-ateiti-aplink-28658423.html",
          "price": "9 400 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 57,
          "item": "ads28658423",
          "details": "Kaunas, Panemunė, J. Vailokaičio g. 8.00 a |  Namų valda",
          "filter_name": "sklypas",
          "id": 2474,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Parduodamas sklypas Kaune, Rokeliuose,",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-sklypas-kaune-rokeliuose-suduviu-gatveje-sklypo-29146055.html",
          "price": "7 600 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 57,
          "item": "ads29146055",
          "details": "Kaunas, Panemunė, Sūduvių g. 8.45 a |  Namų valda",
          "filter_name": "sklypas",
          "id": 2476,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Parduodamas 9.36 a Namų Valdos Sklypas Prie",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-9-36-a-namu-valdos-sklypas-prie-ezero-aukstojoje-29370075.html",
          "price": "10 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 57,
          "item": "ads29370075",
          "details": "Kaunas, Panemunė, J. Totoraičio g. 9.36 a |  Namų valda",
          "filter_name": "sklypas",
          "id": 2478,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Kauno m. sav., Kauno m., Panemunė",
          "url": "https://www.skelbiu.lt/skelbimai/kauno-m-sav-kauno-m-panemune-27965219.html",
          "price": "7 750 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 57,
          "item": "ads27965219",
          "details": "Kaunas, Panemunė, Orijos g. 8.75 a |  Namų valda",
          "filter_name": "sklypas",
          "id": 2479,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Parduodamas 8.51 a namų valdos sklypas",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-8-51-a-namu-valdos-sklypas-krackiemio-g-18-27542037.html",
          "price": "9 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 57,
          "item": "ads27542037",
          "details": "Kaunas, Panemunė, Kračkiemio g. 8.51 a |  Namų valda",
          "filter_name": "sklypas",
          "id": 2481,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Parduodamas namų valdos sklypas Pastogės g. 4",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-namu-valdos-sklypas-pastoges-g-4-vienkiemiu-g-29780165.html",
          "price": "9 500 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 57,
          "item": "ads29780165",
          "details": "Kaunas, Vaišvydava, Pastogės g. 8.79 a |  Namų valda",
          "filter_name": "sklypas",
          "id": 2482,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Ieškote ramios vietos namo statybai gamtoje,",
          "url": "https://www.skelbiu.lt/skelbimai/ieskote-ramios-vietos-namo-statybai-gamtoje-bet-netoli-28574437.html",
          "price": "8 930 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 57,
          "item": "ads28574437",
          "details": "Kaunas, Vaišvydava, Liepaloto g. 8.93 a |  Namų valda",
          "filter_name": "sklypas",
          "id": 2485,
          "added_on": "2017-07-06T07:38:15"
        }
      ],
      "filter_name": "sklypas",
      "deactivation_token": "abc"
    },
    "60": {
      "items": [
        {
          "title": "Kotedžas Su Vieta Dviviečiui Garažui\r",
          "url": "https://www.skelbiu.lt/skelbimai/kotedzas-su-vieta-dvivieciui-garazui-ramioje-saugioje-29173595.html",
          "price": "66 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29173595",
          "details": "Kaunas, Romainiai 85 m² |  2.50 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2449,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Parduodamas kotedžas Seniavos pl. Aleksote, Kaunas",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-kotedzas-seniavos-pl-aleksote-kaunas-bendras-29508535.html",
          "price": "68 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29508535",
          "details": "Kaunas, Aleksotas, Seniavos pl. 112 m² |  3.00 a |  4 kamb. |  Neįrengtas |  Dujinis",
          "filter_name": "namas",
          "id": 2452,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Parduodami dvibuciai namai Z. Kaniukuose",
          "url": "https://www.skelbiu.lt/skelbimai/parduodami-dvibuciai-namai-z-kaniukuose-28145813.html",
          "price": "49 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28145813",
          "details": "Kaunas, Lampėdžiai, P. Leono g. 80 m² |  10.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis |  Elektra",
          "filter_name": "namas",
          "id": 2454,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Panemunės parke pusė namo su 10 arų žemės",
          "url": "https://www.skelbiu.lt/skelbimai/panemunes-parke-puse-namo-su-10-aru-zemes-noredami-29642271.html",
          "price": "32 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29642271",
          "details": "Kaunas, Panemunė, Vaišvydavos pl. 80 m² |  10.00 a |  5 kamb. |  Įrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2455,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Parduodamas 80 kv.m. namas su žemės sklypu,",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-80-kv-m-namas-su-zemes-sklypu-girios-g-106-29808379.html",
          "price": "66 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29808379",
          "details": "Kaunas, Romainiai, Girios g. 80 m² |  3.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2458,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Parduodamas dvibutis 80 kv.m. kotedžas su",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-dvibutis-80-kv-m-kotedzas-su-zemes-sklypu-girios-29808377.html",
          "price": "66 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29808377",
          "details": "Kaunas, Romainiai, Girios g. 80 m² |  3.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2460,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Parduodamas naujos statybos vieno aukšto 80",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-naujos-statybos-vieno-auksto-80-kv-m-sublokuotas-29808021.html",
          "price": "66 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29808021",
          "details": "Kaunas, Romainiai, Girios g. 80 m² |  3.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2463,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Parduodamas naujos statybos 2 aukštų 80 kv.m.",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-naujos-statybos-2-aukstu-80-kv-m-atskiras-namas-29808019.html",
          "price": "66 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29808019",
          "details": "Kaunas, Romainiai, Girios g. 80 m² |  3.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2466,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Dvibutis Kotedžas, 4 kambariai, per du",
          "url": "https://www.skelbiu.lt/skelbimai/dvibutis-kotedzas-4-kambariai-per-du-aukstus-salia-sargenu-29804051.html",
          "price": "90 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29804051",
          "details": "Kaunas, Sargėnai, Žiburių g. 107 m² |  2.80 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2469,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Naujos statybos du dvibučiai namai, juose yra",
          "url": "https://www.skelbiu.lt/skelbimai/naujos-statybos-du-dvibuciai-namai-juose-yra-4-kambariai-29801841.html",
          "price": "86 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29801841",
          "details": "Kaunas, Sargėnai, Žiburių g. 107 m² |  2.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2470,
          "added_on": "2017-07-06T07:38:14"
        },
        {
          "title": "Parduodama Namo Dalis (2-3 Aukštai) Mūriniame",
          "url": "https://www.skelbiu.lt/skelbimai/parduodama-namo-dalis-2-3-aukstai-muriniame-name-29787659.html",
          "price": "50 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29787659",
          "details": "Kaunas, Kleboniškis, Kleboniškio g. 140 m² |  5.00 a |  5 kamb. |  Įrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2473,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Parduodami A Energinio Naudingumo Klasės",
          "url": "https://www.skelbiu.lt/skelbimai/parduodami-a-energinio-naudingumo-klases-namai-igulos-namu-29784463.html",
          "price": "67 900 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29784463",
          "details": "Kaunas, Sargėnai, Įgulos g. 78 m² |  3.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2475,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Parduodami A klasės naujai statomi kotedžai",
          "url": "https://www.skelbiu.lt/skelbimai/parduodami-a-klases-naujai-statomi-kotedzai-e-levino-g-29781899.html",
          "price": "79 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29781899",
          "details": "Kaunas, Romainiai, E. Levino g. 99 m² |  2.50 a |  5 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2477,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Projektas \" Purienų Namai",
          "url": "https://www.skelbiu.lt/skelbimai/projektas-purienu-namai-purienu-namai-atsiperkanti-gyvenimo-29772219.html",
          "price": "57 900 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29772219",
          "details": "Kaunas, Aleksotas, Purienų g. 80 m² |  2.50 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2480,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Parduodamas 100 kv.m. butas Verkių g. Butas",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-100-kv-m-butas-verkiu-g-butas-yra-tribucio-namo-29768269.html",
          "price": "53 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29768269",
          "details": "Kaunas, Aukštieji Šančiai, Verkių g. 180 m² |  3.00 a |  4 kamb. |  Įrengtas |  Kitoks",
          "filter_name": "namas",
          "id": 2483,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Parduodami vieno aukšto namukai Vaišvydavoje,",
          "url": "https://www.skelbiu.lt/skelbimai/parduodami-vieno-auksto-namukai-vaisvydavoje-kaune-9-29765515.html",
          "price": "56 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29765515",
          "details": "Kaunas, Vaišvydava, Garšvės g. 80 m² |  4.00 a |  4 kamb. |  Neįrengtas |  Elektra",
          "filter_name": "namas",
          "id": 2484,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": " naujas 74 namų kvartalas Kaune. ",
          "url": "https://www.skelbiu.lt/skelbimai/naujas-74-namu-kvartalas-kaune-a-klases-vieno-auksto-namai-29764367.html",
          "price": "82 900 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29764367",
          "details": "Kaunas, Šilainiai, A. Šapokos g. 80 m² |  4.50 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2486,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Parduodamas erdvus 143.80 kv.m. dvibutis",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-erdvus-143-80-kv-m-dvibutis-kotedzas-su-garazu-29764319.html",
          "price": "82 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29764319",
          "details": "Kaunas, Romainiai, Lubinų g. 144 m² |  4.50 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2487,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Parduodamas namas Kaune, Grigo g.",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-namas-kaune-grigo-g-bendras-plotas-321-kv-m-29761987.html",
          "price": "83 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29761987",
          "details": "Kaunas, Panemunė, N. Grigo g. 321 m² |  10.00 a |  6 kamb. |  Įrengtas |  Dujinis",
          "filter_name": "namas",
          "id": 2488,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Parduodamas suremontuotas namas Sargėnuose",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-suremontuotas-namas-sargenuose-visas-i-asis-namo-29761855.html",
          "price": "79 900 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29761855",
          "details": "Kaunas, Sargėnai, Pienių g. 97 m² |  6.00 a |  4 kamb. |  Įrengtas |  Centrinis kolektorinis",
          "filter_name": "namas",
          "id": 2489,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Kraštinis Kotedžas Su 3 Arais Žemės\r",
          "url": "https://www.skelbiu.lt/skelbimai/krastinis-kotedzas-su-3-arais-zemes-aprasymas-bendras-plotas-29761683.html",
          "price": "52 500 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29761683",
          "details": "Kaunas, Aleksotas, Seniavos pl. 74 m² |  3.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2490,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Renovuotas Namas Labai Ramioje Vietoje A.",
          "url": "https://www.skelbiu.lt/skelbimai/renovuotas-namas-labai-ramioje-vietoje-a-sanciuose-aprasymas-29761375.html",
          "price": "89 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29761375",
          "details": "Kaunas, Aukštieji Šančiai 105 m² |  6.00 a |  4 kamb. |  Įrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2491,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Parduodami Kotedžai Romainiuose Su Didesniu",
          "url": "https://www.skelbiu.lt/skelbimai/parduodami-kotedzai-romainiuose-su-didesniu-sklypu-paskutine-29752199.html",
          "price": "67 500 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29752199",
          "details": "Kaunas, Romainiai, Girios g. 105 m² |  3.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2492,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Namas mūrinis A.šančiai Prancūzų g.",
          "url": "https://www.skelbiu.lt/skelbimai/namas-murinis-a-sanciai-prancuzu-g-27355275.html",
          "price": "89 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads27355275",
          "details": "Kaunas, Aukštieji Šančiai, Prancūzų g. 105 m² |  6.00 a |  5 kamb. |  Įrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2493,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Aleksote sublokuoti 2-jų dalių namai",
          "url": "https://www.skelbiu.lt/skelbimai/aleksote-sublokuoti-2-ju-daliu-namai-noredami-susisiekti-su-29735667.html",
          "price": "74 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29735667",
          "details": "Kaunas, Aleksotas, Seniavos pl. 98 m² |  2.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis |  Kietu kuru",
          "filter_name": "namas",
          "id": 2494,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Vaišvydavoje Parduodamas Kotedžas Tribučiame",
          "url": "https://www.skelbiu.lt/skelbimai/vaisvydavoje-parduodamas-kotedzas-tribuciame-naujos-statybos-29726209.html",
          "price": "50 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29726209",
          "details": "Kaunas, Vaišvydava, E. Pliaterytės g. 88 m² |  1.00 a |  4 kamb. |  Dalinė apdaila |  Kitoks",
          "filter_name": "namas",
          "id": 2495,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Prestižinėje Miesto Vietoje Žaliakalnyje",
          "url": "https://www.skelbiu.lt/skelbimai/prestizineje-miesto-vietoje-zaliakalnyje-parduodama-4-29724739.html",
          "price": "34 900 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29724739",
          "details": "Kaunas, Žaliakalnis, Raseinių g. 86 m² |  1.80 a |  4 kamb. |  Įrengtas |  Centrinis",
          "filter_name": "namas",
          "id": 2496,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "„pUrienų Namai“- atsiperkanti gyvenimo",
          "url": "https://www.skelbiu.lt/skelbimai/purienu-namai-atsiperkanti-gyvenimo-investicija-penki-faktai-29724699.html",
          "price": "65 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29724699",
          "details": "Kaunas, Aleksotas, Purienų g. 89 m² |  2.50 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2497,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Ramioje Aleksoto Vietoje, Bartelių G.,",
          "url": "https://www.skelbiu.lt/skelbimai/ramioje-aleksoto-vietoje-barteliu-g-parduodama-namo-dalis-su-29718209.html",
          "price": "79 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29718209",
          "details": "Kaunas, Aleksotas, Bartelių g. 192 m² |  5.33 a |  4 kamb. |  Įrengtas |  Dujinis",
          "filter_name": "namas",
          "id": 2498,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Parduodamas Kraštinis Kotedžas",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-krastinis-kotedzas-unikalumu-issiskiriantys-29716239.html",
          "price": "77 500 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29716239",
          "details": "Kaunas, Romainiai 102 m² |  4.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2499,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Parduodamas ekonomiškas A klasės 100 kv.m.",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-ekonomiskas-a-klases-100-kv-m-kotedzas-priklauso-29716003.html",
          "price": "79 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29716003",
          "details": "Kaunas, Romainiai, Kudrėnų g. 100 m² |  3.50 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2500,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Išskirtinėje Romainių Vietoje, Pavėjuonio G.,",
          "url": "https://www.skelbiu.lt/skelbimai/isskirtineje-romainiu-vietoje-pavejuonio-g-parduodamas-namas-29705991.html",
          "price": "82 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29705991",
          "details": "Kaunas, Romainiai, Pavejuonio g. 140 m² |  14.00 a |  5 kamb. |  Įrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2501,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Parduodami Dvibučiai Ir Tribučiai Naujos",
          "url": "https://www.skelbiu.lt/skelbimai/parduodami-dvibuciai-ir-tribuciai-naujos-statybos-103-kv-m-29704433.html",
          "price": "86 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29704433",
          "details": "Kaunas, Sargėnai, Dobilų g. 103 m² |  2.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2502,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Parduodamas Mūrinis Namas Aleksote!\r",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-murinis-namas-aleksote-irengimas-119-58-kv-m-29704327.html",
          "price": "65 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29704327",
          "details": "Kaunas, Aleksotas, Rožių g. 120 m² |  8.28 a |  6 kamb. |  Įrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2503,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Parduodamas 126 kv.m. namas su 13,65 a. žemės",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-126-kv-m-namas-su-13-65-a-zemes-sklypu-aleksote-29699787.html",
          "price": "87 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29699787",
          "details": "Kaunas, Aleksotas, Europos pr. 126 m² |  13.65 a |  8 kamb. |  Įrengtas |  Dujinis",
          "filter_name": "namas",
          "id": 2504,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Name yra visos komunikacijos: vanduo, dujos,",
          "url": "https://www.skelbiu.lt/skelbimai/name-yra-visos-komunikacijos-vanduo-dujos-29314727.html",
          "price": "90 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29314727",
          "details": "Kaunas, Aleksotas, Vaivorykštės al. 190 m² |  6.00 a |  4 kamb. |  Įrengtas |  Dujinis |  Kietu kuru",
          "filter_name": "namas",
          "id": 2505,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Parduodamas 4 k. 81,5 kv.m. dvibutis namas",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-4-k-81-5-kv-m-dvibutis-namas-kaune-silainiuose-k-29683277.html",
          "price": "65 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29683277",
          "details": "Kaunas, Šilainiai, K. Čerbulėno g. 82 m² |  3.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2506,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "! Tik 1 Kilometras Nuo Senamiesčio, Namas",
          "url": "https://www.skelbiu.lt/skelbimai/tik-1-kilometras-nuo-senamiescio-namas-zaliakalnyje-su-29675839.html",
          "price": "37 900 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29675839",
          "details": "Kaunas, Žaliakalnis, Vaisių g. 93 m² |  4.73 a |  5 kamb. |  Įrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2507,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "! Tik 1 Kilometras Nuo Senamiesčio, Namo",
          "url": "https://www.skelbiu.lt/skelbimai/tik-1-kilometras-nuo-senamiescio-namo-dalis-zaliakalnyje-29675837.html",
          "price": "37 900 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29675837",
          "details": "Kaunas, Žaliakalnis, Vaisių g. 187 m² |  4 kamb. |  Įrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2508,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "D.namo (2 aukštas) Žaliakalnyje Raseinių g.",
          "url": "https://www.skelbiu.lt/skelbimai/d-namo-2-aukstas-zaliakalnyje-raseiniu-g-noredami-susisiekti-29669549.html",
          "price": "79 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29669549",
          "details": "Kaunas, Žaliakalnis, Raseinių g. 91 m² |  4.00 a |  5 kamb. |  Įrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2509,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Planuojama statybos darbų pabaiga (su daline",
          "url": "https://www.skelbiu.lt/skelbimai/planuojama-statybos-darbu-pabaiga-su-daline-apdaila-2017-m-29625137.html",
          "price": "69 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29625137",
          "details": "Kaunas, Romainiai, Lubinų g. 90 m² |  2.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2510,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Parduodamas 80 M2 Namas Su Daline Apdaila",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-80-m2-namas-su-daline-apdaila-romainiuose-29625057.html",
          "price": "67 999 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29625057",
          "details": "Kaunas, Romainiai, Lubinų g. 80 m² |  2.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2511,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Parduodamas geros būklės kokybiškai",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-geros-bukles-kokybiskai-pastatytas-gyvenamas-29628949.html",
          "price": "48 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29628949",
          "details": "Kaunas, Freda, J. Bakanausko g. 111 m² |  4.00 a |  5 kamb. |  Įrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2512,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Namas Su Sklypu, Visomis Komunikacijomis,",
          "url": "https://www.skelbiu.lt/skelbimai/namas-su-sklypu-visomis-komunikacijomis-panemuneje-aprasymas-29603157.html",
          "price": "62 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29603157",
          "details": "Kaunas, Panemunė, J. Staugaičio g. 90 m² |  8.40 a |  4 kamb. |  Įrengtas |  Dujinis",
          "filter_name": "namas",
          "id": 2513,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Parduodama 100 Kv.m. Namo Dalis Nuostabioje",
          "url": "https://www.skelbiu.lt/skelbimai/parduodama-100-kv-m-namo-dalis-nuostabioje-vietoje-salia-29602999.html",
          "price": "70 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29602999",
          "details": "Kaunas, Žaliakalnis, Minties Rato g. 100 m² |  3.00 a |  5 kamb. |  Įrengtas |  Dujinis",
          "filter_name": "namas",
          "id": 2514,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Atskiras Namas Šilainiuose \r",
          "url": "https://www.skelbiu.lt/skelbimai/atskiras-namas-silainiuose-aprasymas-bendras-plotas-81-5-kv-29602827.html",
          "price": "68 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29602827",
          "details": "Kaunas, Šilainiai, K. Čerbulėno g. 82 m² |  3.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2515,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Šviežias Projektas Šilainiuose \r",
          "url": "https://www.skelbiu.lt/skelbimai/sviezias-projektas-silainiuose-aprasymas-bendras-plotas-74-29602787.html",
          "price": "58 600 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29602787",
          "details": "Kaunas, Šilainiai, K. Čerbulėno g. 75 m² |  3.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2516,
          "added_on": "2017-07-06T07:38:15"
        },
        {
          "title": "Vieno aukšto individualus namas su nuosavu 4",
          "url": "https://www.skelbiu.lt/skelbimai/vieno-auksto-individualus-namas-su-nuosavu-4-aru-sklypu-29581853.html",
          "price": "89 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29581853",
          "details": "Kaunas, Romainiai, Lubinų g. 89 m² |  4.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2517,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Parduodamas 78 m² su 3 arų sklypu dvibutis –",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-78-m-su-3-aru-sklypu-dvibutis-kotedzas-29578553.html",
          "price": "65 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29578553",
          "details": "Kaunas, Romainiai, Liucijanavos g. 78 m² |  3.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2518,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "A klasės kotedžas, Aleksote, Seniavos pl. 56e",
          "url": "https://www.skelbiu.lt/skelbimai/a-klases-kotedzas-aleksote-seniavos-pl-56e-namas-pastatytas-29577201.html",
          "price": "52 500 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29577201",
          "details": "Kaunas, Aleksotas, Seniavos pl. 74 m² |  2.50 a |  4 kamb. |  Neįrengtas |  Elektra |  Dujinis",
          "filter_name": "namas",
          "id": 2519,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Parduodama tvarkinga namo dalis Žaliakalnyje,",
          "url": "https://www.skelbiu.lt/skelbimai/parduodama-tvarkinga-namo-dalis-zaliakalnyje-ypac-ramioje-29568477.html",
          "price": "72 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29568477",
          "details": "Kaunas, Žaliakalnis, Kapsų g. 113 m² |  4.00 a |  5 kamb. |  Įrengtas |  Dujinis |  Kietu kuru",
          "filter_name": "namas",
          "id": 2520,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Šiuolaikiški, Kokybiški Kotedžai Geroje Vietoje!\r",
          "url": "https://www.skelbiu.lt/skelbimai/siuolaikiski-kokybiski-kotedzai-geroje-vietoje-parduodami-29552311.html",
          "price": "78 750 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29552311",
          "details": "Kaunas, Šilainiai, Tyrlaukio g. 105 m² |  2.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2521,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Parduodama Namo Dalis Arba Keturių Kambarių",
          "url": "https://www.skelbiu.lt/skelbimai/parduodama-namo-dalis-arba-keturiu-kambariu-butas-privaciu-29548479.html",
          "price": "55 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29548479",
          "details": "Kaunas, Žaliakalnis, Zanavykų g. 118 m² |  3.00 a |  4 kamb. |  Įrengtas |  Dujinis |  Kietu kuru",
          "filter_name": "namas",
          "id": 2522,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Kaune, Sargėnuose, Vandžiogalos pl. 108,",
          "url": "https://www.skelbiu.lt/skelbimai/kaune-sargenuose-vandziogalos-pl-108-parduodamas-butas-per-2-29542453.html",
          "price": "77 900 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29542453",
          "details": "Kaunas, Sargėnai, Vandžiogalos g. 116 m² |  3.00 a |  4 kamb. |  Įrengtas |  Dujinis",
          "filter_name": "namas",
          "id": 2523,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Šiuolaikiški, Kokybiški Kotedžai Geroje Vietoje!\r",
          "url": "https://www.skelbiu.lt/skelbimai/siuolaikiski-kokybiski-kotedzai-geroje-vietoje-nuolaida-iki-29533337.html",
          "price": "55 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29533337",
          "details": "Kaunas, Romainiai, Eidintų g. 79 m² |  2.10 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2524,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Kotedžas Su Vieta Garažui/stoginei, 5-ių Arba",
          "url": "https://www.skelbiu.lt/skelbimai/kotedzas-su-vieta-garazui-stoginei-5-iu-arba-4-iu-kambariu-29531991.html",
          "price": "64 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29531991",
          "details": "Kaunas, Romainiai, Pakaunės g. 91 m² |  3.00 a |  5 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2525,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Trijų butu kotedžai Aleksote kraštinis",
          "url": "https://www.skelbiu.lt/skelbimai/triju-butu-kotedzai-aleksote-krastinis-noredami-susisiekti-29526315.html",
          "price": "52 500 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29526315",
          "details": "Kaunas, Aleksotas, Seniavos pl. 105 m² |  2.00 a |  4 kamb. |  Neįrengtas |  Dujinis",
          "filter_name": "namas",
          "id": 2526,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Namas Žaliakalnyje Ievų take",
          "url": "https://www.skelbiu.lt/skelbimai/namas-zaliakalnyje-ievu-take-noredami-susisiekti-su-brokeriu-29524387.html",
          "price": "50 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29524387",
          "details": "Kaunas, Žaliakalnis, Ievų takas 137 m² |  6.00 a |  5 kamb. |  Įrengtas |  Kitoks",
          "filter_name": "namas",
          "id": 2527,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Parduodama didzioji namo dalis",
          "url": "https://www.skelbiu.lt/skelbimai/parduodama-didzioji-namo-dalis-29521939.html",
          "price": "45 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29521939",
          "details": "Kaunas, Aleksotas 170 m² |  6.00 a |  5 kamb. |  Neįrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2528,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Parduodamas medinis namas Kaune,ringuvos gatvėje",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-medinis-namas-kaune-ringuvos-gatveje-29502191.html",
          "price": "65 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29502191",
          "details": "Kaunas, Ž. Šančiai, Ringuvos g. 74 m² |  3.00 a |  4 kamb. |  Įrengtas |  Dujinis |  Kietu kuru",
          "filter_name": "namas",
          "id": 2529,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Vieta!\r",
          "url": "https://www.skelbiu.lt/skelbimai/vieta-ypatingai-grazioje-kauno-vietoje-priesais-romainiu-29498043.html",
          "price": "75 500 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29498043",
          "details": "Kaunas, Romainiai, J. Semaškos g. 146 m² |  6.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis |  Kietu kuru",
          "filter_name": "namas",
          "id": 2530,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Parduoda savininkas.\r",
          "url": "https://www.skelbiu.lt/skelbimai/parduoda-savininkas-kaune-aleksote-barteliu-g-parduodamas-29489383.html",
          "price": "86 900 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29489383",
          "details": "Kaunas, Aleksotas, Bartelių g. 122 m² |  8.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2531,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Kaunas, Panemunė, Bernardinų Plytinės g., 4 kambar",
          "url": "https://www.skelbiu.lt/skelbimai/kaunas-panemune-bernardinu-plytines-g-4-kambar-29479219.html",
          "price": "71 200 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29479219",
          "details": "Kaunas, Panemunė, Bernardinų Plytinės g. 90 m² |  6.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2532,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Parduodu namą",
          "url": "https://www.skelbiu.lt/skelbimai/parduodu-nama-29463753.html",
          "price": "80 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29463753",
          "details": "Kaunas 78 m² |  5.00 a |  4 kamb. |  Dalinė apdaila |  Kietu kuru",
          "filter_name": "namas",
          "id": 2533,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Parduodami vieno aukšto namukai Vaišvydavoje,",
          "url": "https://www.skelbiu.lt/skelbimai/parduodami-vieno-auksto-namukai-vaisvydavoje-kaune-9-29449391.html",
          "price": "83 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29449391",
          "details": "Kaunas, Vaišvydava, Garšvės g. 80 m² |  4.00 a |  4 kamb. |  Dalinė apdaila |  Elektra",
          "filter_name": "namas",
          "id": 2534,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Parduodama namo dalis, Aleksote",
          "url": "https://www.skelbiu.lt/skelbimai/parduodama-namo-dalis-aleksote-noredami-susisiekti-su-29705633.html",
          "price": "17 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29705633",
          "details": "Kaunas, Aleksotas, H. ir O. Minkovskių g. 112 m² |  4.00 a |  6 kamb. |  Įrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2535,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Nedidelis gyvenamas namas",
          "url": "https://www.skelbiu.lt/skelbimai/nedidelis-gyvenamas-namas-11537189.html",
          "price": "83 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads11537189",
          "details": "Kaunas, Aleksotas, Z. Tiškos g. 170 m² |  6.00 a |  4 kamb.",
          "filter_name": "namas",
          "id": 2536,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Be tarpininkų parduodamas naujos statybos (",
          "url": "https://www.skelbiu.lt/skelbimai/be-tarpininku-parduodamas-naujos-statybos-krastinis-dvieju-29401333.html",
          "price": "87 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29401333",
          "details": "Kaunas, Šilainiai, A. Šapokos g. 105 m² |  4.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2537,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Parduodamas Namas Su Garažu Ir Net Su 5 Arų",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-namas-su-garazu-ir-net-su-5-aru-zemes-sklypu-29400897.html",
          "price": "87 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29400897",
          "details": "Kaunas, Šilainiai 128 m² |  5.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2538,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Parduodamas gyvenamasis namas Vaišvydavos",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-gyvenamasis-namas-vaisvydavos-gyvenvieteje-namas-29381741.html",
          "price": "89 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29381741",
          "details": "Kaunas, Vaišvydava, Mergasalio g. 120 m² |  14.94 a |  4 kamb. |  Įrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2539,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Kaune, Aleksote, Balbieriškio g. parduodama",
          "url": "https://www.skelbiu.lt/skelbimai/kaune-aleksote-balbieriskio-g-parduodama-murinio-namo-100-kv-29381505.html",
          "price": "53 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29381505",
          "details": "Kaunas, Aleksotas, Balbieriškio g. 100 m² |  5.00 a |  6 kamb. |  Įrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2540,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Parduodamas namas komercijai patogioje",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-namas-komercijai-patogioje-vietoje-didelis-29361997.html",
          "price": "89 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29361997",
          "details": "Kaunas, Vilijampolė, Varnių g. 142 m² |  8.00 a |  7 kamb. |  Įrengtas |  Elektra",
          "filter_name": "namas",
          "id": 2541,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Kaune, Aleksote, Rąžės gt. 37, parduodamas",
          "url": "https://www.skelbiu.lt/skelbimai/kaune-aleksote-razes-gt-37-parduodamas-nebaigtas-irengti-29359259.html",
          "price": "79 900 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29359259",
          "details": "Kaunas, Aleksotas, Rąžės g. 132 m² |  6.00 a |  5 kamb. |  Dalinė apdaila |  Dujinis |  Kietu kuru",
          "filter_name": "namas",
          "id": 2542,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Liko 1 Kotedžas!\r",
          "url": "https://www.skelbiu.lt/skelbimai/liko-1-kotedzas-bene-greciausiai-besivystanciame-romainiuose-29359167.html",
          "price": "60 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29359167",
          "details": "Kaunas, Romainiai, Meldų g. 102 m² |  5.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2543,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Parduodami 3 sublokuoti kotedžai 2 iš jų",
          "url": "https://www.skelbiu.lt/skelbimai/parduodami-3-sublokuoti-kotedzai-2-is-ju-krastiniai-namai-29351441.html",
          "price": "89 600 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29351441",
          "details": "Kaunas, Romainiai, J. Okso g. 102 m² |  2.60 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2544,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Gyvenamasis namas",
          "url": "https://www.skelbiu.lt/skelbimai/gyvenamasis-namas-29348727.html",
          "price": "30 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29348727",
          "details": "Kaunas, Krioklio g. 86 m² |  15.00 a |  4 kamb. |  Kitas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2545,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Namas Kaune, Rokų g.",
          "url": "https://www.skelbiu.lt/skelbimai/namas-kaune-roku-g-29336681.html",
          "price": "87 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29336681",
          "details": "Kaunas, Rokų g. 159 m² |  17.00 a |  4 kamb. |  Įrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2546,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Parduodamas 129 Kv.m.ploto Namas, Ramioje",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-129-kv-m-ploto-namas-ramioje-vietoje-29331923.html",
          "price": "62 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29331923",
          "details": "Kaunas, Vilijampolė, Kalnų g. 129 m² |  6.00 a |  6 kamb. |  Įrengtas |  Dujinis |  Kietu kuru",
          "filter_name": "namas",
          "id": 2547,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "3000 Eur Akcija! Paskutinis dvibutis",
          "url": "https://www.skelbiu.lt/skelbimai/3000-eur-akcija-paskutinis-dvibutis-kotedzas-sargenuose-su-5-29323921.html",
          "price": "85 999 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29323921",
          "details": "Kaunas, Sargėnai, Dobilų g. 126 m² |  5.00 a |  4 kamb. |  Dalinė apdaila |  Elektra",
          "filter_name": "namas",
          "id": 2548,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Namas su sklypu Aleksote",
          "url": "https://www.skelbiu.lt/skelbimai/namas-su-sklypu-aleksote-29311053.html",
          "price": "60 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29311053",
          "details": "Kaunas, Aleksotas, Liepų g. 100 m² |  7.00 a |  8 kamb. |  Įrengtas |  Dujinis",
          "filter_name": "namas",
          "id": 2549,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Akcija – 64.000 € iki liepos 1 d. Vėliau",
          "url": "https://www.skelbiu.lt/skelbimai/akcija-64-000-iki-liepos-1-d-veliau-kaina-kils-liko-29304229.html",
          "price": "64 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29304229",
          "details": "Kaunas, Dainava, Chemijos g. 100 m² |  3.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2550,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Parduodamas Gyvenamas Namas Palemone, Kaune",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-gyvenamas-namas-palemone-kaune-privalumai-ramus-29291453.html",
          "price": "42 500 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29291453",
          "details": "Kaunas, Palemonas, Gastilonių g. 127 m² |  5.77 a |  7 kamb. |  Įrengtas |  Centrinis",
          "filter_name": "namas",
          "id": 2551,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "2017 M. Naujas Projektas! Du Namai Su Stoginėmis!\r",
          "url": "https://www.skelbiu.lt/skelbimai/2017-m-naujas-projektas-du-namai-su-stoginemis-puikioje-29289693.html",
          "price": "69 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29289693",
          "details": "Kaunas, Romainiai, Romainių g. 83 m² |  3.40 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2552,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Sprendiniai, Lemiantys Vertę:\r",
          "url": "https://www.skelbiu.lt/skelbimai/sprendiniai-lemiantys-verte-optimaliai-isnaudotas-vidaus-29289491.html",
          "price": "89 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29289491",
          "details": "Kaunas, Vytėnai, Salantų g. 87 m² |  2.50 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2553,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Parduodamas 160 kv.m. namas Narsiečiuose,",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-160-kv-m-namas-narsieciuose-raitininku-g-kaina-29259921.html",
          "price": "81 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29259921",
          "details": "Kaunas, Aleksotas, Raitininkų g. 160 m² |  6.00 a |  4 kamb. |  Įrengtas |  Dujinis |  Kietu kuru",
          "filter_name": "namas",
          "id": 2554,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Individualus Namas Už Kotedžo Kainą Mieste!",
          "url": "https://www.skelbiu.lt/skelbimai/individualus-namas-uz-kotedzo-kaina-mieste-parduodami-siuo-29256161.html",
          "price": "69 900 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29256161",
          "details": "Kaunas, Aleksotas, Karininkų aklg. 93 m² |  4.00 a |  4 kamb. |  Neįrengtas |  Dujinis",
          "filter_name": "namas",
          "id": 2555,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Ramioje vietoje netoli Kauno marių parduodami",
          "url": "https://www.skelbiu.lt/skelbimai/ramioje-vietoje-netoli-kauno-mariu-parduodami-du-muriniai-29224279.html",
          "price": "85 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29224279",
          "details": "Kaunas, Palemonas, Marių g. 122 m² |  20.00 a |  5 kamb. |  Neįrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2556,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Kotedžas Su Vieta Garažui\r",
          "url": "https://www.skelbiu.lt/skelbimai/kotedzas-su-vieta-garazui-darbu-su-pilna-apdaila-pabaiga-29224181.html",
          "price": "84 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29224181",
          "details": "Kaunas, Romainiai, Pakaunės g. 90 m² |  3.00 a |  4 kamb. |  Įrengtas |  Dujinis",
          "filter_name": "namas",
          "id": 2557,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Parduodamas kraštinis kotedžas Lubinų gatvėje",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-krastinis-kotedzas-lubinu-gatveje-sklypo-plotas-29221965.html",
          "price": "61 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29221965",
          "details": "Kaunas, Romainiai, Lubinų g. 97 m² |  3.00 a |  4 kamb. |  Įrengtas |  Dujinis",
          "filter_name": "namas",
          "id": 2558,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Parduoda Tiesiogiai Statytojas,be tarpininkų!",
          "url": "https://www.skelbiu.lt/skelbimai/parduoda-tiesiogiai-statytojas-be-tarpininku-liko-tik-vienas-29162311.html",
          "price": "69 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29162311",
          "details": "Kaunas, Romainiai, Lubinų g. 90 m² |  2.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2559,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Parduodamas 4 kmbr. 81,5 kv.m. namas Kaune,",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-4-kmbr-81-5-kv-m-namas-kaune-silainiuose-k-29151939.html",
          "price": "70 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29151939",
          "details": "Kaunas, Šilainiai, K. Čerbulėno g. 82 m² |  4.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2560,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Parduodamas 4 kmbr. 81,5 kv.m. dvibutis namas",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-4-kmbr-81-5-kv-m-dvibutis-namas-kaune-29151927.html",
          "price": "65 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29151927",
          "details": "Kaunas, Šilainiai, K. Čerbulėno g. 82 m² |  3.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2561,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Parduodamas Dviejų Aukštų Namas F. Kiršos G.,",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-dvieju-aukstu-namas-f-kirsos-g-vaisvydavoje-29107397.html",
          "price": "79 900 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29107397",
          "details": "Kaunas, Vaišvydava, F. Kiršos g. 350 m² |  10.00 a |  4 kamb. |  Įrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2562,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Parduodamas Dviejų Aukštų Namas F. Kiršos G.,",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-dvieju-aukstu-namas-f-kirsos-g-vaisvydavoje-29107287.html",
          "price": "84 900 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29107287",
          "details": "Kaunas, Vaišvydava, F. Kiršos g. 350 m² |  15.09 a |  4 kamb. |  Įrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2563,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "Naujienos:-",
          "url": "https://www.skelbiu.lt/skelbimai/naujienos-2017-06-30-sumontuoti-kondensaciniai-katilai-ir-29290757.html",
          "price": "79 900 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29290757",
          "details": "Kaunas, Sargėnai, Agronomijos g. 106 m² |  12.00 a |  4 kamb. |  Dalinė apdaila |  Elektra |  Dujinis",
          "filter_name": "namas",
          "id": 2564,
          "added_on": "2017-07-06T07:38:16"
        },
        {
          "title": "_",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-94-kv-m-kotedzas-panemuneje-projekto-privalumai-29077149.html",
          "price": "79 900 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29077149",
          "details": "Kaunas, Panemunė, Plento g. 94 m² |  2.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2565,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Gal svajojate apie erdvų namą dideliame",
          "url": "https://www.skelbiu.lt/skelbimai/gal-svajojate-apie-erdvu-nama-dideliame-sklype-salia-misko-29500997.html",
          "price": "45 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29500997",
          "details": "Kaunas, Romainiai 203 m² |  17.00 a |  4 kamb. |  Pamatai |  Kitoks |  Dujinis",
          "filter_name": "namas",
          "id": 2566,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Parduodamas Namas Žaliakalnyje!",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-namas-zaliakalnyje-raseiniu-gatve-puiki-vieta-29063033.html",
          "price": "32 500 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29063033",
          "details": "Kaunas, Žaliakalnis, Raseinių g. 86 m² |  1.59 a |  7 kamb. |  Kitas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2567,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Parduodami du namai erdviame sklype Marių g.,",
          "url": "https://www.skelbiu.lt/skelbimai/parduodami-du-namai-erdviame-sklype-mariu-g-palemone-prie-29044079.html",
          "price": "85 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29044079",
          "details": "Kaunas, Palemonas, Marių g. 121 m² |  20.00 a |  5 kamb. |  Neįrengtas |  Elektra |  Skystu kuru |  Kietu kuru",
          "filter_name": "namas",
          "id": 2568,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Labai Šilti, Kokybiški Namai!\r",
          "url": "https://www.skelbiu.lt/skelbimai/labai-silti-kokybiski-namai-isskirtinis-a-klases-9-29005719.html",
          "price": "83 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29005719",
          "details": "Kaunas, Vaišvydava, Garšvės g. 80 m² |  4.00 a |  4 kamb. |  Dalinė apdaila |  Kitoks",
          "filter_name": "namas",
          "id": 2569,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Parduodamas КOtedzas Su Zemes Sklypu.\r",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-kotedzas-su-zemes-sklypu-aprasymas-bendras-28995369.html",
          "price": "84 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28995369",
          "details": "Kaunas, Šilainiai, A. Šapokos g. 112 m² |  3.00 a |  4 kamb. |  Įrengtas |  Dujinis",
          "filter_name": "namas",
          "id": 2570,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Parduodamas 4 k. 81,5 kv.m. krastinis namas",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-4-k-81-5-kv-m-krastinis-namas-su-pastogine-28987063.html",
          "price": "68 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28987063",
          "details": "Kaunas, Šilainiai, K. Čerbulėno g. 82 m² |  3.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2571,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "„tAuro Vartai“ – tai naujas darnaus gyvenimo",
          "url": "https://www.skelbiu.lt/skelbimai/tauro-vartai-tai-naujas-darnaus-gyvenimo-pavyzdys-kotedzu-ir-28967893.html",
          "price": "68 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28967893",
          "details": "Kaunas, Aleksotas, Versmės g. 80 m² |  2.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2572,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Parduodamas erdvus, 120 kv.m., gyvenamas",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-erdvus-120-kv-m-gyvenamas-medinis-namas-su-3-5-a-28947469.html",
          "price": "69 500 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28947469",
          "details": "Kaunas, Šilainiai, J. Grušo g. 120 m² |  3.50 a |  4 kamb. |  Įrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2573,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Namas Vilijampolėje",
          "url": "https://www.skelbiu.lt/skelbimai/namas-vilijampoleje-28941555.html",
          "price": "85 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28941555",
          "details": "Kaunas, Vilijampolė, J. Vienožinskio g. 120 m² |  3.00 a |  6 kamb. |  Įrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2574,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "„tAuro Vartai“ – tai naujas darnaus gyvenimo",
          "url": "https://www.skelbiu.lt/skelbimai/tauro-vartai-tai-naujas-darnaus-gyvenimo-pavyzdys-kotedzu-ir-28897167.html",
          "price": "67 999 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28897167",
          "details": "Kaunas, Aleksotas, Versmės g. 80 m² |  2.00 a |  4 kamb. |  Įrengtas |  Dujinis",
          "filter_name": "namas",
          "id": 2575,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Palemone, Marių g., parduodama dalis namo su",
          "url": "https://www.skelbiu.lt/skelbimai/palemone-mariu-g-parduodama-dalis-namo-su-6-65-a-sklypu-28825265.html",
          "price": "54 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28825265",
          "details": "Kaunas, Palemonas, Marių g. 107 m² |  6.65 a |  4 kamb. |  Įrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2576,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Parduodamas Aleksote mūrinis namas su kieme",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-aleksote-murinis-namas-su-kieme-esanciu-ukiniu-28817311.html",
          "price": "48 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28817311",
          "details": "Kaunas, Aleksotas, Kalkinės g. 128 m² |  6.50 a |  4 kamb. |  Neįrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2577,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Būsto kredito mėnesinė įmoka apie 260€",
          "url": "https://www.skelbiu.lt/skelbimai/busto-kredito-menesine-imoka-apie-260-parduodami-aukstos-28936367.html",
          "price": "65 900 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28936367",
          "details": "Kaunas, Šilainiai, Saulės g. 80 m² |  2.50 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2578,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Parduodamas individualus namas !\r",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-individualus-namas-sklypas-10aru-atidalinta-29799797.html",
          "price": "65 900 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29799797",
          "details": "Kaunas, Romainiai, Šilagirio g. 80 m² |  4.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2579,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Parduodama Dalis Namo A. Juozapavačiaus Pr",
          "url": "https://www.skelbiu.lt/skelbimai/parduodama-dalis-namo-a-juozapavaciaus-pr-kaune-zemieji-28683007.html",
          "price": "88 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28683007",
          "details": "Kaunas, Ž. Šančiai, A. Juozapavičiaus pr. 274 m² |  5.68 a |  6 kamb. |  Kitas |  Centrinis",
          "filter_name": "namas",
          "id": 2580,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Parduodamas 108 m² su 3 arų sklypu, ypač",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-108-m-su-3-aru-sklypu-ypac-kokybiskas-kotedzas-28312029.html",
          "price": "86 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28312029",
          "details": "Kaunas, Freda, J. Pabrėžos g. 108 m² |  3.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2581,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Parduodamas Dalis Namo Su Sklypu Kalniečiuose",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-dalis-namo-su-sklypu-kalnieciuose-puikioje-28283841.html",
          "price": "79 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28283841",
          "details": "Kaunas, Žaliakalnis, Sukilėlių pr. 92 m² |  5.60 a |  5 kamb. |  Įrengtas |  Dujinis",
          "filter_name": "namas",
          "id": 2582,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Parduodamas Individualus Namas A.panemunėje\r",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-individualus-namas-a-panemuneje-galima-namo-28273337.html",
          "price": "39 999 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28273337",
          "details": "Kaunas, Panemunė, Gervuogių takas 199 m² |  6.83 a |  6 kamb. |  Neįrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2583,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Parduodamas 145,61 Kv. M. Mūrinis Namas Fredoje",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-145-61-kv-m-murinis-namas-fredoje-parduodamas-28239075.html",
          "price": "90 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28239075",
          "details": "Kaunas, Freda, Gvazdikų g. 146 m² |  7.76 a |  5 kamb. |  Įrengtas |  Dujinis",
          "filter_name": "namas",
          "id": 2584,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Puikioje miesto vietoje Aleksote, F.",
          "url": "https://www.skelbiu.lt/skelbimai/puikioje-miesto-vietoje-aleksote-f-vaitkaus-g-parduodama-med-29352273.html",
          "price": "48 500 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29352273",
          "details": "Kaunas, Aleksotas, F. Vaitkaus g. 62 m² |  2.50 a |  4 kamb. |  Įrengtas |  Dujinis |  Kietu kuru",
          "filter_name": "namas",
          "id": 2585,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Parduodamas medinis apmūrytas namas su 5,26 a",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-medinis-apmurytas-namas-su-5-26-a-privaciu-29660877.html",
          "price": "79 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29660877",
          "details": "Kaunas, Vilijampolė, Atramos g. 120 m² |  5.26 a |  5 kamb. |  Įrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2586,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Parduodamas Naujos Statybos Kotedžas Privačių",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-naujos-statybos-kotedzas-privaciu-namu-kvartale-28490117.html",
          "price": "85 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28490117",
          "details": "Kaunas, Sargėnai, Dobilų g. 103 m² |  2.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2587,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Nejudrioje, apšviestoje gatvelėje, netoli",
          "url": "https://www.skelbiu.lt/skelbimai/nejudrioje-apsviestoje-gatveleje-netoli-pagrindines-28106783.html",
          "price": "65 900 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28106783",
          "details": "Kaunas, Romainiai, Liucijanavos g. 107 m² |  2.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2588,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Parduodamas 2 a. mūrinis namas Amaliuose",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-2-a-murinis-namas-amaliuose-guobu-g-bendras-28003095.html",
          "price": "60 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28003095",
          "details": "Kaunas, Dainava, Guobų g. 148 m² |  6.00 a |  6 kamb. |  Įrengtas |  Dujinis",
          "filter_name": "namas",
          "id": 2589,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Ramioje, Jaukioje Vietoje, Individualių Namų",
          "url": "https://www.skelbiu.lt/skelbimai/ramioje-jaukioje-vietoje-individualiu-namu-kvartale-28922749.html",
          "price": "61 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28922749",
          "details": "Kaunas, Romainiai, Vijūkų g. 100 m² |  1.50 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2590,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Parduodama Dalis Mūrinio Namo Amaliuose",
          "url": "https://www.skelbiu.lt/skelbimai/parduodama-dalis-murinio-namo-amaliuose-puikus-pasirinkimas-27939109.html",
          "price": "57 500 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads27939109",
          "details": "Kaunas, Petrašiūnai, Jerubių takas 85 m² |  3.00 a |  4 kamb. |  Įrengtas |  Dujinis",
          "filter_name": "namas",
          "id": 2591,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Ramioje, Jaukioje Vietoje, Individualių Namų",
          "url": "https://www.skelbiu.lt/skelbimai/ramioje-jaukioje-vietoje-individualiu-namu-kvartale-28922747.html",
          "price": "77 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28922747",
          "details": "Kaunas, Romainiai, Vijūkų g. 100 m² |  4.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2592,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Ramioje, Jaukioje Vietoje, Individualių Namų",
          "url": "https://www.skelbiu.lt/skelbimai/ramioje-jaukioje-vietoje-individualiu-namu-kvartale-27851641.html",
          "price": "67 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads27851641",
          "details": "Kaunas, Romainiai, Vijūkų g. 100 m² |  1.50 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2593,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Ramioje, Jaukioje Vietoje, Individualių Namų",
          "url": "https://www.skelbiu.lt/skelbimai/ramioje-jaukioje-vietoje-individualiu-namu-kvartale-27851637.html",
          "price": "72 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads27851637",
          "details": "Kaunas, Romainiai, Vijūkų g. 100 m² |  2.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2594,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Žaliakalnyje ,strategiškai patogioje vietoje",
          "url": "https://www.skelbiu.lt/skelbimai/zaliakalnyje-strategiskai-patogioje-vietoje-labai-ramioje-28967541.html",
          "price": "74 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28967541",
          "details": "Kaunas, Žaliakalnis, Nevėžio g. 125 m² |  3.20 a |  6 kamb. |  Įrengtas |  Dujinis",
          "filter_name": "namas",
          "id": 2595,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "A energinės klasės gyvenamūjų namų kvartalas",
          "url": "https://www.skelbiu.lt/skelbimai/a-energines-klases-gyvenamuju-namu-kvartalas-yra-skirtas-27406447.html",
          "price": "83 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads27406447",
          "details": "Kaunas, Vaišvydava, Garšvės g. 78 m² |  4.25 a |  4 kamb. |  Įrengtas |  Elektra",
          "filter_name": "namas",
          "id": 2596,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Ramioje miesto vietoje, Aleksote, parduodama",
          "url": "https://www.skelbiu.lt/skelbimai/ramioje-miesto-vietoje-aleksote-parduodama-dalis-gyvenamo-27064143.html",
          "price": "26 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads27064143",
          "details": "Kaunas, Aleksotas, S. Dariaus ir S. Girėno g. 81 m² |  4.80 a |  4 kamb. |  Įrengtas |  Kitoks",
          "filter_name": "namas",
          "id": 2597,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Parduodamas kokybiškai pastatytas kotedžas su",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-kokybiskai-pastatytas-kotedzas-su-autonominiu-28936379.html",
          "price": "60 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28936379",
          "details": "Kaunas, Šilainiai, Slyvų g. 87 m² |  2.50 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2598,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "„pEitupės namai“ tai uždaras keturių",
          "url": "https://www.skelbiu.lt/skelbimai/peitupes-namai-tai-uzdaras-keturiu-vienbuciu-namu-kvartalas-26941151.html",
          "price": "83 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads26941151",
          "details": "Kaunas, Romainiai, E. Volterio g. 85 m² |  4.00 a |  5 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2599,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Yra Kampinių Kotedžų !\r",
          "url": "https://www.skelbiu.lt/skelbimai/yra-kampiniu-kotedzu-isskirtinis-objektas-vystomas-naujas-29666611.html",
          "price": "58 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29666611",
          "details": "Kaunas, Romainiai, Šilagirio g. 95 m² |  2.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2600,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Parduodamas 79,94  kv.m. kotedžas O.milašiaus",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-79-94-kv-m-kotedzas-o-milasiaus-g-fredoje-kauno-28494521.html",
          "price": "78 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28494521",
          "details": "Kaunas, Freda, O. Milašiaus g. 80 m² |  1.70 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2601,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Nuosavas namas - tai vieta Jūsų vaizduotei ir",
          "url": "https://www.skelbiu.lt/skelbimai/nuosavas-namas-tai-vieta-jusu-vaizduotei-ir-kurybiskumui-26597283.html",
          "price": "83 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads26597283",
          "details": "Kaunas, Aleksotas, Raitininkų g. 174 m² |  6.00 a |  5 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2602,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Liko Tik Du Namai\r",
          "url": "https://www.skelbiu.lt/skelbimai/liko-tik-du-namai-kotedzai-salia-nevezio-slaito-9-km-iki-26572835.html",
          "price": "73 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads26572835",
          "details": "Kaunas, Romainiai, E. Volterio g. 94 m² |  2.00 a |  4 kamb. |  Dalinė apdaila |  Dujinis",
          "filter_name": "namas",
          "id": 2603,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Parduodamas namas Vilijampolėje, Naujalio g.",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-namas-vilijampoleje-naujalio-g-namas-400-kv-m-26549281.html",
          "price": "76 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads26549281",
          "details": "Kaunas, Vilijampolė, J. Naujalio g. 400 m² |  6.00 a |  4 kamb. |  Įrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2604,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Parduodamas Individualus Gyvenamasis Namas\r",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-individualus-gyvenamasis-namas-aleksote-kalkines-25905801.html",
          "price": "35 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads25905801",
          "details": "Kaunas, Aleksotas, Kalkinės g. 80 m² |  6.00 a |  4 kamb. |  Įrengtas |  Kietu kuru",
          "filter_name": "namas",
          "id": 2605,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "-  -\r",
          "url": "https://www.skelbiu.lt/skelbimai/www-vaisvydavosnamai-lt-kontaktai-869801170-vaisvydovos-28746729.html",
          "price": "79 200 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28746729",
          "details": "Kaunas, Vaišvydava, Garšvės g. 80 m² |  5.40 a |  4 kamb. |  Dalinė apdaila |  Elektra |  Kitoks",
          "filter_name": "namas",
          "id": 2606,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "„pEitupės namai“ tai uždaras keturių",
          "url": "https://www.skelbiu.lt/skelbimai/peitupes-namai-tai-uzdaras-keturiu-vienbuciu-namu-kvartalas-24336653.html",
          "price": "69 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads24336653",
          "details": "Kaunas, Romainiai, E. Volterio g. 85 m² |  5.00 a |  5 kamb. |  Neįrengtas |  Dujinis",
          "filter_name": "namas",
          "id": 2607,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Žaliakalnyje prestižinėje ramioje vietoje",
          "url": "https://www.skelbiu.lt/skelbimai/zaliakalnyje-prestizineje-ramioje-vietoje-parduodamas-dvieju-28965305.html",
          "price": "72 000 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads28965305",
          "details": "Kaunas, Žaliakalnis, Minties Rato g. 86 m² |  3.00 a |  6 kamb. |  Neįrengtas |  Elektra |  Skystu kuru |  Kitoks |  Dujinis |  Kietu kuru",
          "filter_name": "namas",
          "id": 2608,
          "added_on": "2017-07-06T07:38:17"
        },
        {
          "title": "Parduodamas nebaigtas statyti murinis namukas",
          "url": "https://www.skelbiu.lt/skelbimai/parduodamas-nebaigtas-statyti-murinis-namukas-yra-ir-naujas-29137617.html",
          "price": "62 268 €",
          "is_new": 1,
          "email": "chyzas@gmail.com",
          "filter": 60,
          "item": "ads29137617",
          "details": "Kaunas, Kleboniškis 90 m² |  7.30 a |  4 kamb. |  Nebaigtas statyti |  Kitoks",
          "filter_name": "namas",
          "id": 2609,
          "added_on": "2017-07-06T07:38:17"
        }
      ],
      "filter_name": "namas",
      "deactivation_token": "abc"
    }
  },
  "email": "chyzas@gmail.com",
  "template": "results",
  "subject": "Nauji skelbiu skelbimai"
}';
        return new Message($msgBig, 'aa');
        try {
            $result = $this->client->receiveMessage([
                'QueueUrl' => $this->url
            ]);
            if ($result['Messages'] == null) {
                return false;
            }
            $result_message = array_pop($result['Messages']);

            return new Message($result_message['Body'], $result_message['ReceiptHandle']);
        } catch (Exception $e) {

        }
    }

    public function delete(Message $message)
    {
        try {
            $this->client->deleteMessage(array(
                'QueueUrl' => $this->url,
                'ReceiptHandle' => $message->getReceiptHandler()
            ));

            return true;
        } catch (Exception $e) {
            echo 'Error deleting message from queue ' . $e->getMessage();

            return false;
        }
    }
}
