#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
#
#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register
#
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting
#
#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile

app_filter:
    resource: "@AppBundle/Resources/config/routing/filter.yml"
    prefix:   /user/filter

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    pattern: /login/check-facebook

sif_home_page:
  path: /
  defaults: { _controller: AppBundle:Default:index }

sif_submit:
  path: /submit
  methods: ['POST']
  defaults: { _controller: AppBundle:Default:submit }


confirmation:
  path: /confirm/{token}
  defaults: { _controller: AppBundle:User:confirm }

app_activate_filter:
  path: /filter/activate/{token}
  defaults: { _controller: AppBundle:Filter:activateFilter }

app_deactivate_filter:
  path: /filter/deactivate/{token}
  defaults: { _controller: AppBundle:Filter:deactivate }

app_test:
  path: /test
  defaults: { _controller: AppBundle:TestResults:test}
